language: node_js
sudo: required

dist: bionic

node_js:
  - 12

cache:
  yarn: true
  directories:
    - ./node_modules

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.21.1-1

stages:
  - test
  - name: build
    if: branch = master AND type != pull_request
  - name: build-docs
    if: branch = master AND type != pull_request

jobs:
   include:
    - stage: test
      name: "Lint, Test and CodeCoverage"
      script:
        - yarn lint
        - yarn test
        - codecov

    - stage: build
      name: "Building angular-mdc-web"
      script: yarn run build:release

    - stage: build-docs
      name: "Building and Deploying documentation"
      script:
        - cd demos
        - npm install
        - npm install -g @angular/cli
        - rm -rf node_modules/@material/data-table/*.ts # Remove if #1959 is fixed
        - rm -rf ../node_modules/@material/data-table/*.ts # Remove if #1959 is fixed
        - ng build --prod
      deploy:
        provider: pages
        github_token: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        keep_history: true
        committer_from_gh: true
        local_dir: demos/dist/angular-mdc-demos/
        on:
            branch: master
